version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: crimewatch_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ['5432:5432']
